# Generated by Django 2.0.1 on 2019-11-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
