# Generated by Django 2.0.1 on 2019-11-13 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_auto_20191112_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user_name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='execution.User'),
            preserve_default=False,
        ),
    ]
