# Generated by Django 2.0.1 on 2019-11-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_data_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user_name',
            new_name='aa',
        ),
    ]
