# Generated by Django 2.0.1 on 2019-11-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_auto_20191113_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='aa',
            new_name='user_name',
        ),
    ]
