# Generated by Django 2.0.1 on 2019-11-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_auto_20191113_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='data',
            name='blog_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='blog_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.User'),
        ),
    ]
