# Generated by Django 2.0.1 on 2019-11-13 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_auto_20191113_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
