# Generated by Django 2.0.1 on 2019-11-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0008_auto_20191113_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user_name',
        ),
        migrations.AddField(
            model_name='data',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
