# Generated by Django 2.0.1 on 2019-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_data_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
