# Generated by Django 2.0.1 on 2019-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_data_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
