# Generated by Django 2.0.1 on 2019-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0017_tag_post_data_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
