# Generated by Django 2.0.1 on 2019-11-20 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0020_auto_20191120_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 20, 12, 8, 31, 174726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
