# Generated by Django 2.0.1 on 2019-11-20 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0021_auto_20191120_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 20, 12, 8, 32, 17228, tzinfo=utc)),
        ),
    ]
