# Generated by Django 2.0.1 on 2019-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0022_auto_20191120_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
